In [89]:
from sklearn.feature_extraction.text import CountVectorizer

import pandas as pd

#to avoid future warning
#import warnings
#warnings.simplefilter(action='ignore', category=FutureWarning)

In [90]:
vect = CountVectorizer()

In [91]:
messages = ["Hey hey hey lets go get lunch today..!",
            "Did you go home?..",
            "Hey!!! I need a favor"]

using fit method ,CountVectorizer() will learn what tokens are being used in our messages

In [92]:
vect.fit(messages)

CountVectorizer()

In [93]:
vect.get_feature_names()

['did',
 'favor',
 'get',
 'go',
 'hey',
 'home',
 'lets',
 'lunch',
 'need',
 'today',
 'you']

In [94]:
x_new = vect.fit_transform(messages).toarray()

In [95]:
x_new

array([[0, 0, 1, 1, 3, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [96]:
#x_new = vect.fit_transform(messages).toarray()

In [97]:
vect.get_feature_names()

['did',
 'favor',
 'get',
 'go',
 'hey',
 'home',
 'lets',
 'lunch',
 'need',
 'today',
 'you']

- By using the get_feature_name() method ,we can see what features
  have been created from our messages.(or what tokens have been learned by CountVectorizer)

In [98]:
df = pd.DataFrame(x_new,columns = vect.get_feature_names())
print (df)

   did  favor  get  go  hey  home  lets  lunch  need  today  you
0    0      0    1   1    3     0     1      1     0      1    0
1    1      0    0   1    0     1     0      0     0      0    1
2    0      1    0   0    1     0     0      0     1      0    0


### Let's read text data from  a file and try to convert it into numeric form

In [99]:
df = pd.read_csv('Restaurant_Reviews.tsv',sep='\t')

In [100]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [101]:
df.shape

(1000, 2)

In [102]:
df.Liked.value_counts()  #to display no. of samples for each unique value

1    500
0    500
Name: Liked, dtype: int64

In [103]:
import re

In [104]:
def clean(x):
    
    #remove all html tags from data
    #remove all numbers from data
    #remove all special chars from data
    #remove stop words
    #stemming
    #lemmitization
    #etc..
    s = re.sub('<.*?>',' ',x) #remove html tags
    
    s = re.sub('[^A-Za-z]',' ',s)  
    #to replace everything except A-Z or a-z with ' '(single space)
    
    s = re.sub('\s+',' ',s)       
    #to replace more than one space's with single space only
    
    s = s.strip()    
    #remove spaces from either from beginning or end of string
    
    return s.lower()    #return string in lower case
    
    

In [105]:
clean('hello python 123hi #@ <html>ok</html>')

'hello python hi ok'

In [106]:
df['Review'] = df.Review.apply(clean)

In [107]:
df.head()

Review  Liked
0                               wow loved this place      1
1                                  crust is not good      0
2           not tasty and the texture was just nasty      0
3  stopped by during the late may bank holiday of...      1
4  the selection on the menu was great and so wer...      1

In [108]:
X = df.Review.values
y = df.Liked.values

In [109]:
#from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\risha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [110]:
#words = stopwords.words('english')

In [111]:
#print(words)

In [112]:
#if 'not' in words:
 #   words.remove('not')

In [113]:
#stop.append()

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=.2,random_state=12)

In [116]:
cv = CountVectorizer()

In [117]:
cv_train = cv.fit_transform(xtrain)  #for training data

cv_test = cv.transform(xtest)        #for testing data

In [118]:
#cv.get_stop_words()

In [119]:
#for i in list(cv.get_stop_words()):
#    print(i, end=',')

In [120]:
#if 'not' in list(cv.get_stop_words()):
 #   print('Yes it exists!')

In [ ]:
cv.get_feature_names()

In [122]:
cv_train.shape

(800, 1776)

In [123]:
len(cv.get_feature_names())

1776

In [124]:
from sklearn.linear_model import LogisticRegression
#from sklearn.metrics import accuracy_score

In [125]:
log = LogisticRegression()

In [126]:
log.fit(cv_train,ytrain)

pred = log.predict(cv_test)

#score = accuracy_score(ytest,pred)
#score
score = log.score(cv_test,ytest)
score

0.78

In [127]:
pred

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1], dtype=int64)

In [128]:
test = ['food was 123@#$ good']

In [129]:
cleaned_data=[]

for i in test:
    t = clean(i)
    cleaned_data.append(t)

In [130]:
cleaned_data

['food was good']

In [131]:
t1 = cv.transform(cleaned_data)

In [132]:
t1.shape

(1, 1776)

In [133]:
log.predict(t1)

array([1], dtype=int64)

In [134]:
########################################### 2 Way : Importing a text file and performing extraction ##########################

In [135]:
from sklearn.feature_extraction.text import CountVectorizer

import pandas as pd

In [136]:
df =pd.read_csv('IMDB Dataset.csv')

In [137]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [138]:
df.iloc[4,0]

'Petter Mattei\'s "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler\'s play about the same theme, the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. Stylishly, the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case wit

In [139]:
df.shape

(50000, 2)

In [140]:
df.sentiment.value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [141]:
import re

In [142]:
def clean(x):
    
    #remove all html tags from data
    #remove all numbers from data
    #remove all special chars from data
    #remove stop words
    #stemming
    #lemmitization
    #etc..
    
    s = re.sub('<.*?>',' ',x) #remove html tags
    
    s = re.sub('[^A-Za-z]',' ',s)  
    #to replace everything except A-Z or a-z with ' '(single space)
    
    s = re.sub('\s+',' ',s)       
    #to replace more than one space's with single space only
    
    s = s.strip()    
    #remove spaces from either from beginning or end of string
    
    return s.lower()    #return string in lower case

In [143]:
df['review'] = df.review.apply(clean)

In [144]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s love in the time of money is a...  positive

In [145]:
df.iloc[0].review

'one of the other reviewers has mentioned that after watching just oz episode you ll be hooked they are right as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to many aryans muslims gangstas latinos christians italians irish and more so scuffles death stares dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows wouldn t dare forget pretty p

In [146]:
X = df.review.values
y = df.sentiment.values

In [147]:
from sklearn.model_selection import train_test_split

In [148]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=.2,random_state=12)

In [149]:
vect = CountVectorizer()

In [150]:
#vect.get_feature_names()

In [151]:
cv_train = vect.fit_transform(xtrain)  #for training data

cv_test = vect.transform(xtest)        #for testing data

In [152]:
#cv.get_stop_words()

In [153]:
cv_train.shape

(40000, 90634)

In [154]:
#len(cv.get_feature_names())

In [155]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [156]:
log = LogisticRegression()

In [157]:
log.fit(cv_train,ytrain)

pred = log.predict(cv_test)

score = accuracy_score(ytest,pred)
score

C:\Users\risha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8874

In [158]:
x =vect.fit_transform(df['review'])

In [159]:
x

<50000x99394 sparse matrix of type '<class 'numpy.int64'>'
	with 6755626 stored elements in Compressed Sparse Row format>

In [ ]:
#vect.get_feature_names()